# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-03 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_newwriting'),
    ]

    operations = [
        migrations.AddField(
            model_name='newwriting',
            name='join',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=5, verbose_name='Want to Join the team?'),
        ),
    ]
