# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170703_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=5),
        ),
    ]
