# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_newwriting_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='YES', max_length=5),
        ),
    ]
